name: docs_rhythmidia
channels:

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - matplotlib
  - scipy
  - pyautogui
  - scikit-image
  - guizero
  - pytest
  - PyWavelets
  



    # Pip-only installs
  - pip:
    - -e ../

